# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI Verify PR, Push, & Deploy

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md" # ignore documentation-only changes
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  workflow_dispatch:

jobs:
  build:
    if: github.event_name != 'push' || github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          echo 'installing dependencies'
          yarn
          echo 'building app'
          yarn build

      - name: Lint
        run: |
          echo 'linting code'
          yarn lint

      - name: Test
        run: |
          echo 'executing tests'
          echo 'yarn cover'

      - name: Deploy
        # if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
