# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI Verify PR & Push

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4

      - name: Runtime ${{ matrix.node-version }} & Dependency setup
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
        run: |
          echo 'installing dependencies'
          yarn

      - name: Build
        run: |
          echo 'building app'
          yarn build

      - name: Lint
        run: |
          echo 'linting code'
          echo 'TODO'

      - name: Test
        run: |
          echo 'executing tests'
          echo 'yarn cover'
